# Generated by Django 5.0.4 on 2024-07-07 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('FR', 'Friend'), ('FO', 'Follower'), ('BL', 'Blocked')], default='FR', max_length=2)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User relations',
            },
        ),
        migrations.AddConstraint(
            model_name='userrelation',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('to')), _negated=True), name='user_and_to_not_equal', violation_error_message='You cannot create a relation with yourself'),
        ),
        migrations.AlterUniqueTogether(
            name='userrelation',
            unique_together={('user', 'to', 'relation')},
        ),
    ]
